# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-15 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_mobile', models.BigIntegerField()),
                ('user_email', models.EmailField(max_length=30)),
                ('password1', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserSellingData',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('bike_name', models.CharField(max_length=30, null=True)),
                ('bike_price', models.IntegerField(null=True)),
                ('bike_old', models.IntegerField(null=True)),
                ('bike_desc', models.CharField(max_length=300, null=True)),
                ('bike_img', models.ImageField(blank=True, max_length=200, null=True, upload_to='bikeimg/%Y/%m/%d/')),
                ('currdata', models.DateField(max_length=100, null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('rel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.UserRegistrationData')),
            ],
        ),
    ]
